baseurl = "https://example.com"
title = "Vellichor Hugo Theme"
author = "mhhollomon"
copyright = "Copyright 2018, Mark Hollomon, parts Copyright © 2008–2018, @JeffProd"
canonifyurls = true
paginate = 3

# Optionally supported.
# If blank or commented out, the code will
# not be included in the header.
#googleAnalytics = "UA-123-45"

theme = "hugo-theme-vellichor"

[taxonomies]
    tag = "tags"
    archive = "archives"

[Social]
    #
    # List of user ids on various Social Platforms.
    # Ones that are not present, are not placed into the footer.
    GitHub   = "userid"
    Facebook = "userid"
    #Twitter  = "userid"
    #Youtube  = "userid"
    #Reddit   = "userid"

[Params]
    #
    # Image to place in the header. Optional.
    # if you don't want this, comment it out.
    # A solid color band will be used instead.
    headerImage = "img/bg-books-pixabay.jpg"
    #
    # This text will be placed just above the posts
    # on each page of the listing.
    # Comment out this line if you don't want anything.
    blogWelcome = "Welcome to my blog!"
    #
    # Format for the posting date. Default, if this setting is missing, is "January 2, 2006"
    postDateFormat = "2006-01-02"
    #
    # If set and true then reading time will be displayed in the post listing.
    showReadingTime = 0
    #
    # Size of social network icons to use small/medium/large
    # the default is large.
    socialIconSize = "large"
